name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # Cache node_modules to speed up subsequent runs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Set the Node.js version you want

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test

      - name: Upload Playwright Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: |
            results
            playwright-report
            test-results.json
          retention-days: 7

      - name: Upload Playwright Screenshots and Videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-artifacts
          path: |
            screenshots
            videos
            traces
          retention-days: 7
